#LIBRARIES += AP_Common
#LIBRARIES += AP_HAL
#LIBRARIES += AP_HAL_Quan
# To include Notify requires pretty much everything
#LIBRARIES += AP_Notify
#LIBRARIES += GCS_MAVLink
#LIBRARIES += AP_GPS
#LIBRARIES += AP_Vehicle
#LIBRARIES += DataFlash
#LIBRARIES += AP_HAL_Empty
#LIBRARIES += AP_HAL_SITL
LIBRARIES += AP_Math
#LIBRARIES += AP_Param
#LIBRARIES += AP_Progmem
#LIBRARIES += StorageManager
LIBRARIES += Filter
