#ifndef AERFPILOT_LIBRARIES_COMPASS_COMPASS_PRODUCT_ID_HPP_INCLUDED
#define AERFPILOT_LIBRARIES_COMPASS_COMPASS_PRODUCT_ID_HPP_INCLUDED


// compass product id
#define AP_COMPASS_TYPE_UNKNOWN         0x00
#define AP_COMPASS_TYPE_HIL             0x01
#define AP_COMPASS_TYPE_HMC5843         0x02
#define AP_COMPASS_TYPE_HMC5883L        0x03
#define AP_COMPASS_TYPE_AK8963_MPU9250  0x06
#define AP_COMPASS_TYPE_AK8963_I2C      0x07
#define AP_COMPASS_TYPE_LSM303D         0x08
#define AP_COMPASS_TYPE_QUAN            0x09

#endif // AERFPILOT_LIBRARIES_COMPASS_COMPASS_PRODUCT_ID_HPP_INCLUDED
